### ISSUE TITLE
/stocks/indicators

### ISSUE THREAD

**Issue by francisffp** [mfinancecombr/site#10]
Mestre,

Este URL não está mais funcionando. Tem como checar?
https://mfinance.com.br/api/v1/stocks/indicators/

Pela pagina web está aparecendo "{
  "message": "Internal Server Error"
}"

**Comment by marcelometal** [comment]
@francisffp vou ver o que pode ter acontecido... mas vc consegue usar assim tb pra pegar mais um:

https://mfinance.com.br/api/v1/stocks/indicators/?symbols=petr4&symbols=petr3

**Comment by marcelometal** [comment]
@francisffp achei um ponto onde quebrava, era no merge do indicador com os detalhes, de alguma forma algum item fica sem detalhes. Mas agora voltou a rota. Logo identifico o item sem detalhes e resolvo =P

valeu pelo report!
