### ISSUE TITLE
Dividendos Stock

### ISSUE THREAD

**Issue by francisffp** [mfinancecombr/site#11]
Bom dia,

Testei dois tickers e não retornam o dividendo, ITSA4 e B3SA3. Tem previsão de correção?

**Comment by marcelometal** [comment]
Olá @francisffp , obrigado por reportar, foi corrigido!

https://mfinance.com.br/api/v1/stocks/dividends/itsa4
https://mfinance.com.br/api/v1/stocks/dividends/b3sa3
