### ISSUE TITLE
Falta de dados de FIIs

### ISSUE THREAD

**Issue by WallaceCostaFerreira** [mfinancecombr/site#18]
Está faltando diversos fundos imobiliários no retorno da lista deles. Retorna total de 379 havendo na bolsa 425

**Comment by jvictor-meli** [comment]
Tbm notei que está faltando dados de dividendos de FIIs.

**Comment by victorskg** [comment]
Tbm notei que está faltando dados de dividendos de FIIs.

**Comment by mkto20** [comment]
Também preciso, notei que as ultimas atualizações de proventos em FII's são de outubro de 2022 =(

**Comment by marcelometal** [comment]
>Está faltando diversos fundos imobiliários no retorno da lista deles. Retorna total de 379 havendo na bolsa 425

Olá acredito que agora as informações dos simbolos foram atualizadas, temos 474 FIIs cadastradas

>Tbm notei que está faltando dados de dividendos de FIIs.
>Também preciso, notei que as ultimas atualizações de proventos em FII's são de outubro de 2022 =(

foram atualizados

Qualquer coisa avisem!
