### ISSUE TITLE
Diferença de valores - Tesouro Direto

### ISSUE THREAD

**Issue by lhsevero** [mfinancecombr/site#2]
Oi Marcelo.

Antes de qualquer coisa, muito boa sua api, parabéns!

Eu estou executando alguns testes e vi que na chamada para o Tesouro Direto o valor da rentabilidade no site do Tesouro está, para o TESOURO IPCA+com juros semestrais 2055 como 4,21, e no retorno da api está 4,46.
Existe alguma diferença de datas entre os valores? 

Para a cotação de um determinado FII que testei também há diferença, mas isso é compreensível por conta do delay de informações da bolsa... 

Atenciosamente,
Luiz Severo

**Comment by marcelometal** [comment]
Olá @lhsevero, valeu!

Sobre o tesouro direto, existe um delay de atualização desses dados, hoje é a cada 2h. Então, pode ser que a API estava com o dado velho quando você olhou. Posso colocar no dado a hora que ele foi atualiado, fica mais facil saber....

FII tem um delay menor, que é ~20min.

**Comment by marcelometal** [comment]
Olá @lhsevero, encontrei um problem na atualização do tesouro direto, vou subir ainda hoje a correção

**Comment by marcelometal** [comment]
@lhsevero, subi a correção, valeu!

**Comment by lhsevero** [comment]
Marcelo, 
Obrigado. Vou testar e se encontrar algo aviso.

**Comment by lhsevero** [comment]
Testei aqui e os valores retornaram iguais, agora 17h20, Me parece que está correto, mas ainda vou testar em horário distintos hoje mais tarde e amanhã.

Via API Tesouro
Tesouro: 2055 / Taxa: 4.18

Via MFinance
FII: Hedge Brasil Shopping FI Imobiliario
Cotação: 208,92
Tesouro: 2055 / Taxa: 4.18

**Comment by lhsevero** [comment]
Marcelo,
Está tudo ok por aqui. As vezes dá uma pequena diferença mas com certeza por conta do delay.
Valeu!
