### ISSUE TITLE
valor incorreto banco do brasil

### ISSUE THREAD

**Issue by rafakwolf** [mfinancecombr/site#24]
olá, tudo bem?

parece que tem algo errado com banco do brasil.

hoje 2024/05/29 o valor tah em torno de 27,43
mas a api tah retornando um numero bem estranho

![image](https://github.com/mfinancecombr/site/assets/2060578/33563aed-76f0-44f1-82e5-a03fe3f3cc05)
 

valeu! ótimo trabalho

**Comment by marcelometal** [comment]
Olá @rafakwolf ,
Corrigido o valor!

Obrigado por avisa! valeu!
