### ISSUE TITLE
FIIs não encontrados

### ISSUE THREAD

**Issue by lhsevero** [mfinancecombr/site#3]
Oi Marcelo.

Estou rodando a chamada para atualizar uma base com cotações de FIIs e alguns deles não estão sendo encontrados.
Por exemplo: KNCR11, JTPR11, KINP11 e alguns outros.

**Comment by marcelometal** [comment]
Olá @lhsevero, atualizei a lista, realmente estava fantando esses e outros.

obrigado pelo report!
