### ISSUE TITLE
Resposta da consulta de lista de FIIs

### ISSUE THREAD

**Issue by marcio-ota** [mfinancecombr/site#8]
Esta retornando diferente do modelo.
https://mfinance.com.br/api/v1/fiis
--- modelo ---
`{ "fiis": [ { "change": 0, ...`
--- resposta ---
`[ { "change":0, ...`

**Comment by marcelometal** [comment]
Olá @marcio-ota,

obrigado por avisar, vai quebrar pra alguns usuários, mas pra manter o padrão arrumei o payload.
