### ISSUE TITLE
Instabilidade na API

### ISSUE THREAD

**Issue by marcio-ota** [mfinancecombr/site#9]
Boa tarde, desde ontem os ativos estao vindo zerados, e tbm nao tem historicos...

**Comment by marcelometal** [comment]
Ola @marcio-ota , pode dar um exemplo, fiz dois testes aqui e veio dados:

https://mfinance.com.br/api/v1/stocks/historicals/SANB3

https://mfinance.com.br/api/v1/stocks/SANB3

**Comment by marcio-ota** [comment]
Ontem final da tarde ate hoje meio dia estavam zerado, inclusive sem nome do ativo (#NA).
Agora tudo certo!

**Comment by marcelometal** [comment]
blz!
